# Generated by Django 4.0.2 on 2022-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_avg_value_alter_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
