# Generated by Django 4.0.2 on 2022-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
    ]
